# Generated by Django 5.2.13 on 2026-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='estimated_arrival',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='estimated_departure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
