# Generated by Django 5.2.13 on 2026-04-26 00:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_location_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBuddyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('preferred_group', models.CharField(choices=[('everyone', 'Barchasi'), ('boys', 'Faqat yigitlar'), ('girls', 'Faqat qizlar'), ('family', 'Oila'), ('group', 'Guruh')], default='everyone', max_length=10)),
                ('people_needed', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('budget_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_type', models.CharField(choices=[('any', 'Ixtiyoriy'), ('own_car', 'Shaxsiy mashina'), ('taxi', 'Taksi'), ('bus', 'Avtobus'), ('train', 'Poyezd'), ('walking', 'Piyoda')], default='any', max_length=15)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Tugatilgan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_posts', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_buddy_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_buddy_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_buddy_requests', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='travel_buddies.travelbuddypost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='travelbuddypost',
            index=models.Index(fields=['location', 'travel_date'], name='travel_budd_locatio_fc6e19_idx'),
        ),
        migrations.AddIndex(
            model_name='travelbuddypost',
            index=models.Index(fields=['status', 'is_active'], name='travel_budd_status_a9e50d_idx'),
        ),
        migrations.AddIndex(
            model_name='travelbuddypost',
            index=models.Index(fields=['user', 'created_at'], name='travel_budd_user_id_e34b54_idx'),
        ),
        migrations.AddIndex(
            model_name='buddyrequest',
            index=models.Index(fields=['to_user', 'status'], name='travel_budd_to_user_0aef19_idx'),
        ),
        migrations.AddIndex(
            model_name='buddyrequest',
            index=models.Index(fields=['from_user', 'status'], name='travel_budd_from_us_c102c8_idx'),
        ),
        migrations.AddIndex(
            model_name='buddyrequest',
            index=models.Index(fields=['post', 'status'], name='travel_budd_post_id_71d2a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buddyrequest',
            unique_together={('from_user', 'post')},
        ),
    ]
