# Generated by Django 5.2.13 on 2026-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='avg_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='location',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='location',
            name='is_family_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_for_group',
            field=models.BooleanField(default=True),
        ),
    ]
