# Generated by Django 5.2.13 on 2026-04-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_avg_duration_location_difficulty_and_more'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_for_group',
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.interest'),
        ),
    ]
