# Generated by Django 5.2.13 on 2026-04-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_options_remove_location_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationimage',
            name='unique_first_image_per_location',
        ),
    ]
