# Generated by Django 5.2.13 on 2026-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_remove_locationimage_unique_first_image_per_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='group_type',
            field=models.CharField(choices=[('large_group', '10-15 kishidan iborat guruh'), ('medium_group', '6-10 kishidan iborat guruh'), ('small_group', '1-5 kishidan iborat guruh'), ('group', 'Guruh shaklda'), ('family_1_child', 'Ota-ona + 1ta yosh bola bn'), ('family_2_children', 'Ota-ona + 2ta yosh bola bn'), ('family_companions', 'Oilaviy hamrohlar'), ('1_2_partners', '1-2 ta sherik bilan'), ('solo', 'Yakka'), ('friends', 'Dostlar bilan')], default='solo', max_length=20, verbose_name='Guruh turi'),
        ),
    ]
