# Generated by Django 5.2.13 on 2026-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
